AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: golang application

Resources:
  GoAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: lambda-handler
      Runtime: go1.x
      Tracing: Active
      Events:
        GoAppApi:
          Type: Api
          Properties:
            Path: /
            Method: POST

Outputs:
  GoAppAPI:
    Description: "API Gateway endpoint URL for Prod environment for GoApp"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  GoAppFunction:
    Description: "GoApp ARN"
    Value: !GetAtt GoAppFunction.Arn

  GoAppFunctionIamRole:
    Description: "Implicit IAM Role created for GoApp"
    Value: !GetAtt GoAppFunctionRole.Arn
